
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab7(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

   my_keyboard mk1(
      .clk(CLOCK_50), 
      .clrn(KEY), 
      .ps2_clk(PS2_CLK),
      .ps2_data(PS2_DAT),
      .keys_times_h(HEX5),
      .keys_times_l(HEX4),
      .ascii_h(HEX3), 
      .ascii_l(HEX2),
      .scancode_h(HEX1),
      .scancode_l(HEX0)
   );


//=======================================================
//  Structural coding
//=======================================================



endmodule
