
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab5(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	ram1 r1(CLOCK_50, KEY[1], ~KEY[0], SW[3:0], SW[9:8], HEX1, HEX0);
	ram2 r2(CLOCK_50, ~KEY[1], ~KEY[0], SW[3:0], SW[9:8], HEX5, HEX4);
	
	assign LEDR = {~KEY[1], KEY[1]};


//=======================================================
//  Structural coding
//=======================================================



endmodule
